In [2]:
import numpy as np
import matplotlib.pyplot as plt
from typing import List, Optional

In [3]:
class Solution:
    def nextPermutation(self, nums: List[int]) -> None:
        """
        Do not return anything, modify nums in-place instead.
        """
        ...

In [4]:
n = [1,2,3]

In [5]:
sol = Solution()
res = sol.nextPermutation(n)
res

In [ ]:
"""            
[1 2 3]   0 1 2
[1 3 2]   0 2 1
[2 1 3]   1 0 2
[2 3 1]   1 2 0
[3 1 2]   2 0 1
[3 2 1]   2 1 0
"""